package com.ssi.fctrading.DataContract;

public class PPMMRAccountResponse {
    public double collateralAsset;
    public double callLMW;
    public double liability;
    public double eeOrigin;
    public double forceLMV;
    public double equity;
    public double ee;
    public double callMargin;
    public double cashBalance;
    public double purchasingPower;
    public double callForcesell;
    public double lmv;
    public double marginCall;
    public double withdrawal;
    public double collateralA;
    public String action;
    public double marginRatio;
    public double debt;
    public double accruedInterest;
    public double holdRight;
    public double preLoan;
    public double fees;
    public double buyUnmatch;
    public double ap;
    public double apT1;
    public double sellUnmatch;
    public double cia;
    public double ar;
    public double arT1;
    public double ppCredit;
    public double creditLimit;
    public double totalAssets;
    public double marginCallLMVSold;
    public double lmvNonMarginable;
    public double eeCredit;
    public double totalEquity;
    public double eE90;
    public double eE80;
    public double eE70;
    public double eE60;
    public double eE50;
}
