name: Publish package to the Github Repository

on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: "14"
          distribution: "adopt"
          cache: maven

      - name: DryRun Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          dry_run: true

      - name: Update pom.xml
        if: steps.semantic.outputs.new_release_published == 'true'
        run: mvn versions:set-property -Dproperty=revision -DnewVersion=${{ steps.semantic.outputs.new_release_version }} -DgenerateBackupPoms=false
      
      - name: Update README.md
        if: steps.semantic.outputs.new_release_published == 'true'
        run: sed -i 's/${{ steps.semantic.outputs.last_release_version }}/'${{ steps.semantic.outputs.new_release_version }}'/' README.md
      
      - name: Publish sample package
        run: mvn clean package

      - name: Publish java package
        run: mvn --batch-mode deploy -Dmaven.test.skip  -pl fctrading-client


      - name: Semantic Release
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: cycjimmy/semantic-release-action@v3